window.guardIcons = {
  "Грифоны": { town: "Замок", icon: "https://static.wikia.nocookie.net/heroes-of-might-and-magic/images/c/c5/Griffin_%28adventure_map%29.gif" },
  "Королевские Грифоны": { town: "Замок", icon: "https://static.wikia.nocookie.net/heroes-of-might-and-magic/images/3/33/Royal_Griffin_%28adventure_map%29.gif" },
  "Лесные Эльфы": { town: "Оплот", icon: "https://static.wikia.nocookie.net/heroes-of-might-and-magic/images/9/92/Wood_Elf_%28adventure_map%29.gif" },
  "Благородные Эльфы": { town: "Оплот", icon: "https://static.wikia.nocookie.net/heroes-of-might-and-magic/images/f/fa/Grand_Elf_%28adventure_map%29.gif" },
  "Каменные Големы": { town: "Башня", icon: "https://static.wikia.nocookie.net/heroes-of-might-and-magic/images/e/e0/Stone_Golem_%28adventure_map%29.gif" },
  "Железные Големы": { town: "Башня", icon: "https://static.wikia.nocookie.net/heroes-of-might-and-magic/images/6/67/Iron_Golem_%28adventure_map%29.gif" },
  "Адские Гончие": { town: "Инферно", icon: "https://static.wikia.nocookie.net/heroes-of-might-and-magic/images/f/ff/Hell_Hound_%28adventure_map%29.gif" },
  "Церберы": { town: "Инферно", icon: "https://static.wikia.nocookie.net/heroes-of-might-and-magic/images/c/c8/Cerberus_%28adventure_map%29.gif" },
  "Духи": { town: "Некрополис", icon: "https://static.wikia.nocookie.net/heroes-of-might-and-magic/images/2/24/Wight_%28adventure_map%29.gif" },
  "Привидения": { town: "Некрополис", icon: "https://static.wikia.nocookie.net/heroes-of-might-and-magic/images/c/cb/Wraith_%28adventure_map%29.gif" },
  "Бехолдеры": { town: "Темница", icon: "https://static.wikia.nocookie.net/heroes-of-might-and-magic/images/a/ad/Beholder_%28adventure_map%29.gif" },
  "Зловещие Глаза": { town: "Темница", icon: "https://static.wikia.nocookie.net/heroes-of-might-and-magic/images/6/6b/Evil_Eye_%28adventure_map%29.gif" },
  "Орки": { town: "Цитадель", icon: "https://static.wikia.nocookie.net/heroes-of-might-and-magic/images/e/e6/Orc_%28HotA%29_%28adventure_map%29.gif" },
  "Вожди Орков": { town: "Цитадель", icon: "https://static.wikia.nocookie.net/heroes-of-might-and-magic/images/4/4c/Orc_Chieftain_%28HotA%29_%28adventure_map%29.gif" },
  "Змии": { town: "Крепость", icon: "https://static.wikia.nocookie.net/heroes-of-might-and-magic/images/d/da/Serpent_Fly_%28adventure_map%29.gif" },
  "Ядовитые Змии": { town: "Крепость", icon: "https://static.wikia.nocookie.net/heroes-of-might-and-magic/images/9/91/Dragon_Fly_%28adventure_map%29.gif" },
  "Водные Элементали": { town: "Сопряжение", icon: "https://static.wikia.nocookie.net/heroes-of-might-and-magic/images/3/38/Water_Elemental_%28HotA%29_%28adventure_map%29.gif" },
  "Элементали Льда": { town: "Сопряжение", icon: "https://static.wikia.nocookie.net/heroes-of-might-and-magic/images/2/23/Ice_Elemental_%28adventure_map%29.gif" },
  "Пираты": { town: "Причал", icon: "https://static.wikia.nocookie.net/heroes-of-might-and-magic/images/0/04/Pirate_%28adventure_map%29.gif" },
  "Корсары": { town: "Причал", icon: "https://static.wikia.nocookie.net/heroes-of-might-and-magic/images/e/ed/Corsair_%28adventure_map%29.gif" },
  "Морские Волки": { town: "Причал", icon: "https://static.wikia.nocookie.net/heroes-of-might-and-magic/images/2/2f/Sea_Dog_%28adventure_map%29.gif" },
  "Броненосцы": { town: "Фабрика", icon: "https://static.wikia.nocookie.net/heroes-of-might-and-magic/images/0/02/Armadillo_%28adventure_map%29.gif" },
  "Броненосцы-Вожаки": { town: "Фабрика", icon: "https://static.wikia.nocookie.net/heroes-of-might-and-magic/images/5/5c/Bellwether_Armadillo_%28adventure_map%29.gif" },
  "Мумии": { town: "Нейтральные", icon: "https://static.wikia.nocookie.net/heroes-of-might-and-magic/images/0/08/Mummy_%28adventure_map%29.gif" },
  "Кочевник": { town: "Нейтральные", icon: "https://static.wikia.nocookie.net/heroes-of-might-and-magic/images/0/0b/Nomad_%28HotA%29_%28adventure_map%29.gif" }
};
